{% set name = "css-parser" %}
{% set version = "1.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/css-parser-{{ version }}.tar.gz
  sha256: bf1e972ad33344e93206964fb4cd908d9ddef9fcd0c01fa93e0d734675394363

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - css_parser
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ebook-utils/css-parser
  license_file: LICENSE
  license: LGPL3
  license_family: GPL
  summary: A CSS Cascading Style Sheets library for Python
  dev_url: https://github.com/ebook-utils/css-parser

extra:
  recipe-maintainers:
    - domdfcoding
