{% set name = "css-parser" %}
{% set version = "1.0.8" %}
{% set bundle = "tar.gz" %}
{% set hash = "994d6a0115a8f4e2b6648e2b12733036d05fa164278aa234630c9f03e52c8c80" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip

  run:
    - python

test:
  imports:
    - css_parser

about:
  home: https://github.com/ebook-utils/css-parser
  license_file: LICENSE
  license: LGPL3
  license_family: GPL
  summary: A CSS Cascading Style Sheets library for Python
  dev_url: https://github.com/ebook-utils/css-parser
#  doc_url:
