{% set name = "wheel-filename" %}
{% set version = "1.4.1" %}
{% set bundle = "tar.gz" %}
{% set hash = "e2e1eb0780910a0148358252aad6394cc674250686c56c39aa379493438370b3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip

  run:
    - python

test:
  imports:
    - wheel_filename

about:
  home: https://github.com/jwodder/wheel-filename
  license_file: LICENSE
  license: MIT
  summary: Parse wheel filenames.
  dev_url: https://github.com/jwodder/wheel-filename
