{% set name = "prettyprinter" %}
{% set version = "0.18.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "9fe5da7ec53510881dd35d7a5c677ba45f34cfe6a8e78d1abd20652cf82139a8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip

  run:
    - colorful>=0.4.0
    - Pygments>=2.2.0

test:
  imports:
    - prettyprinter

about:
  home: https://github.com/tommikaikkonen/prettyprinter
  license_file: LICENSE
  license: MIT
  summary: Syntax-highlighting, declarative and composable pretty printer for Python 3.5+
  dev_url: https://github.com/tommikaikkonen/prettyprinter
#  doc_url:
