{% set name = "mistletoe" %}
{% set version = "0.8.1" %}
{% set bundle = "tar.gz" %}
{% set hash = "468c6a42fd98b85e05b318033f63d76e02712e1ea1328a7ebcba7e47fb6f1e41" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip

test:
  imports:
    - mistletoe

about:
  home: https://github.com/miyuchina/mistletoe
  license_file: LICENSE
  license: MIT
  summary: A fast, extensible Markdown parser in pure Python.
  dev_url: https://github.com/miyuchina/mistletoe
#  doc_url:
